Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]Fetching 30 files:   3%|▎         | 1/30 [05:51<2:50:05, 351.92s/it]Fetching 30 files:   7%|▋         | 2/30 [05:53<1:07:55, 145.55s/it]Fetching 30 files:  13%|█▎        | 4/30 [23:02<2:29:45, 345.60s/it]
Traceback (most recent call last):
  File "/home/jmcgrath/Model-RPG/eval.py", line 89, in <module>
    main()
  File "/home/jmcgrath/Model-RPG/eval.py", line 28, in main
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 600, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/transformers/modeling_utils.py", line 311, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4680, in from_pretrained
    checkpoint_files, sharded_metadata = _get_resolved_checkpoint_files(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/transformers/modeling_utils.py", line 1295, in _get_resolved_checkpoint_files
    checkpoint_files, sharded_metadata = get_checkpoint_shard_files(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/transformers/utils/hub.py", line 1110, in get_checkpoint_shard_files
    cached_filenames = cached_files(
                       ^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/transformers/utils/hub.py", line 557, in cached_files
    raise e
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/transformers/utils/hub.py", line 485, in cached_files
    snapshot_download(
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/huggingface_hub/_snapshot_download.py", line 327, in snapshot_download
    thread_map(
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/huggingface_hub/_snapshot_download.py", line 301, in _inner_hf_hub_download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1008, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1161, in _hf_hub_download_to_cache_dir
    _download_to_tmp_and_move(
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1710, in _download_to_tmp_and_move
    xet_get(
  File "/home/jmcgrath/miniconda3/envs/ai-test-py312/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 627, in xet_get
    download_files(
RuntimeError: Data processing error: CAS service error : Reqwest Error: HTTP status client error (401 Unauthorized), domain: https://cas-server.xethub.hf.co/reconstruction/c691ea7fbc138a826ca5179d0de5b073452d9d20143dc01a1defc2d0954a8872
